# -*- coding: utf-8 -*-
"""finalmultimodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IarpSsWYJmWXZtl6UXYLZN1DzViI00Wv
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import tensorflow as tf
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
import numpy as np
from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
#from scipy import interp
from numpy import interp
from sklearn.metrics import roc_auc_score
import os
import numpy as np
import shutil
import time
rootdir= '/content/drive/MyDrive/Plant Guard/data/PlantVillage' #path of the original folder
classes = ['Tomato_healthy', 'Tomato_Late_blight']
!rm -rf './train'
!rm -rf './valid'
for i in classes:
    os.makedirs('./train/' + i)
    os.makedirs('./valid/' + i)
    source = rootdir + '/' + i
    allFileNames = os.listdir(source)
    #print(allFileNames)
    np.random.shuffle(allFileNames)
    test_ratio = 0.25
    train_FileNames, test_FileNames = np.split(np.array(allFileNames),[int(len(allFileNames)* (1 - test_ratio))])
    train_FileNames = [source+'/'+ name for name in train_FileNames.tolist()]
    test_FileNames = [source+'/' + name for name in test_FileNames.tolist()]
    for name in train_FileNames:
        shutil.copy(name,'./train/' + i)
    for name in test_FileNames:
        shutil.copy(name,'./valid/' + i)
# Directory with our training Tomato_healthy pictures
train_healthy_dir = os.path.join('./train/Tomato_healthy')

# Directory with our training Tomato_Late_blight pictures
train_unhealthy_dir = os.path.join('./train/Tomato_Late_blight')

# Directory with our validation Tomato_healthy pictures
valid_healthy_dir = os.path.join('./valid/Tomato_healthy')

# Directory with our validation Tomato_Late_blight pictures
valid_unhealthy_dir = os.path.join('./valid/Tomato_Late_blight')
train_healthy_names = os.listdir(train_healthy_dir)
#print(train_healthy_names[:10])

train_unhealthy_names = os.listdir(train_unhealthy_dir)
#print(train_unhealthy_names[:10])

validation_healthy_names = os.listdir(valid_healthy_dir)
#print(validation_healthy_names[:10])

validation_unhealthy_names = os.listdir(valid_unhealthy_dir)
#print(validation_unhealthy_names[:10])
print('total training Tomato_healthy images:', len(os.listdir(train_healthy_dir)))
print('total training Tomato_unhealthy images:', len(os.listdir(train_unhealthy_dir)))
print('total validation Tomato_healthy images:', len(os.listdir(valid_healthy_dir)))
print('total validation Tomato_unhealthy images:', len(os.listdir(valid_unhealthy_dir)))
# %matplotlib inline

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# Parameters for our graph; we'll output images in a 4x4 configuration
nrows = 4
ncols = 4

# Index for iterating over images
pic_index = 0
# Set up matplotlib fig, and size it to fit 4x4 pics
fig = plt.gcf()
fig.set_size_inches(ncols * 4, nrows * 4)

pic_index += 8
next_healthy_pic = [os.path.join(train_healthy_dir, fname)
                for fname in train_healthy_names[pic_index-8:pic_index]]
next_unhealthy_pic = [os.path.join(train_unhealthy_dir, fname)
                for fname in train_unhealthy_names[pic_index-8:pic_index]]

for i, img_path in enumerate(next_healthy_pic + next_unhealthy_pic):
  # Set up subplot; subplot indices start at 1
  sp = plt.subplot(nrows, ncols, i + 1)
  sp.axis('Off') # Don't show axes (or gridlines)

  img = mpimg.imread(img_path)
  plt.imshow(img)

plt.show()
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# All images will be rescaled by 1./255
train_datagen = ImageDataGenerator(rescale=1/255)
validation_datagen = ImageDataGenerator(rescale=1/255)

# Flow training images in batches of 120 using train_datagen generator
train_generator = train_datagen.flow_from_directory(
        './train/',  # This is the source directory for training images
        classes = ['Tomato_healthy', 'Tomato_Late_blight'],
        target_size=(200, 200),  # All images will be resized to 200x200
        batch_size=120,
        # Use binary labels
        class_mode='binary')

# Flow validation images in batches of 19 using valid_datagen generator
validation_generator = validation_datagen.flow_from_directory(
        './valid/',  # This is the source directory for training images
        classes = ['Tomato_healthy', 'Tomato_Late_blight'],
        target_size=(200, 200),  # All images will be resized to 200x200
        batch_size=19,
        # Use binary labels
        class_mode='binary',
        shuffle=False)


model = Sequential()
model.add(MobileNetV2(include_top = False, weights="imagenet", input_shape=(200, 200, 3)))
model.add(tf.keras.layers.GlobalAveragePooling2D())
model.add(Dense(1, activation = 'sigmoid'))
model.layers[0].trainable = False
model.summary

from tensorflow.keras.optimizers import RMSprop

# model.compile(loss='binary_crossentropy',
#               optimizer=RMSprop(lr=0.001),
#               metrics=['accuracy', tf.keras.metrics.AUC()])

from tensorflow.keras import optimizers

model.compile(optimizer=RMSprop(learning_rate=0.01),
              loss='binary_crossentropy',
              metrics=['accuracy', tf.keras.metrics.AUC()])
#model.compile(optimizer=RMSprop(learning_rate=0.01), loss = 'binary_crossentropy', metrics = [accuracy])
st=time.perf_counter()
history = model.fit(
      train_generator,
      steps_per_epoch=5,
      epochs=10,
      verbose=1,
      validation_data = validation_generator,
      validation_steps=8)
nd=time.perf_counter()
print("train_time: ",nd-st);
model.evaluate(validation_generator)
STEP_SIZE_TEST=validation_generator.n//validation_generator.batch_size
validation_generator.reset()
preds = model.predict(validation_generator,
                      verbose=1)
fpr, tpr, _ = roc_curve(validation_generator.classes, preds)
roc_auc = auc(fpr, tpr)
plt.figure()
lw = 2
plt.plot(fpr, tpr, color='darkorange',
         lw=lw, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=lw, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc="lower right")
plt.show()
model.save("tomato_disease_model.h5")

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, ConfusionMatrixDisplay,
    classification_report
)
import matplotlib.pyplot as plt

# Threshold binary prediction from probabilities
y_true = validation_generator.classes
y_pred_prob = preds.ravel()
y_pred = (y_pred_prob > 0.5).astype(int)

# Compute metrics
acc = accuracy_score(y_true, y_pred)
prec = precision_score(y_true, y_pred)
rec = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)

print("=== Evaluation Metrics ===")
print(f"Accuracy  : {acc:.4f}")
print(f"Precision : {prec:.4f}")
print(f"Recall    : {rec:.4f}")
print(f"F1 Score  : {f1:.4f}")

# Classification Report
print("\n=== Classification Report ===")
print(classification_report(y_true, y_pred, target_names=['Healthy', 'Diseased']))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Healthy', 'Diseased'])
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.show()

# Plot: Training and Validation Accuracy
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

# Plot: Training and Validation Loss
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()

# Plot: Training and Validation AUC
plt.plot(history.history['auc_3'], label='Train AUC')
plt.plot(history.history['val_auc_3'], label='Val AUC')
plt.title('AUC over Epochs')
plt.xlabel('Epoch')
plt.ylabel('AUC')
plt.legend()
plt.grid(True)
plt.show()

!pip install streamlit pyngrok

# Add your ngrok authtoken first if not done already
!ngrok config add-authtoken 2zNROZGWMCWQizOWNWRbAYjTLU1_hKcubuMSCikYkUREuXmZ

# Run streamlit in background
!streamlit run streamlit_app.py &> streamlit_log.txt &

# Setup ngrok tunnel (FIXED)
from pyngrok import ngrok
public_url = ngrok.connect(8501, "http")
print("Streamlit is running at:", public_url)

!pkill streamlit
!pkill ngrok

!ngrok config add-authtoken 2zNROZGWMCWQizOWNWRbAYjTLU1_hKcubuMSCikYkUREuXmZ

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# import streamlit as st
# from tensorflow.keras.models import load_model
# from PIL import Image
# import numpy as np
# 
# st.title("Tomato Leaf Disease Detector with Symptom Influence")
# 
# # Load trained model
# model = load_model("tomato_disease_model.h5")
# 
# # File uploader for Leaf Image
# uploaded_file = st.file_uploader("Upload a tomato leaf image", type=["jpg", "jpeg", "png"])
# 
# # Dropdown for symptom selection (always visible)
# symptom = st.selectbox(
#     "Select Leaf Color/Symptom",
#     [
#         '',  # Default empty option for better UX
#         'Green', 'Yellow', 'Brown', 'Dark Green', 'Pale',
#         'Reddish', 'Black Spots', 'Grayish', 'Wilted Yellow',
#         'Leaf Curling', 'Mixed Colors', 'Mosaic Patterns', 'Purple Edges'
#     ]
# )
# 
# # Add submit button
# submit = st.button("Submit")
# 
# if submit:
#     if not uploaded_file:
#         st.warning("Please upload a tomato leaf image before submitting.")
#     elif not symptom:
#         st.warning("Please select a symptom before submitting.")
#     else:
#         image = Image.open(uploaded_file).resize((200, 200))
#         st.image(image, caption="Uploaded Leaf Image", use_column_width=True)
# 
#         img_array = np.array(image) / 255.0
#         if img_array.shape[-1] == 4:
#             img_array = img_array[..., :3]
#         img_array = np.expand_dims(img_array, axis=0)
# 
#         # Model Prediction
#         pred = model.predict(img_array)[0][0]
# 
#         # Influence confidence based on symptom selection
#         risky_symptoms = [
#             'Black Spots', 'Grayish', 'Wilted Yellow', 'Leaf Curling', 'Mosaic Patterns', 'Purple Edges'
#         ]
#         if symptom in risky_symptoms:
#             adjustment = 0.1  # Increase disease confidence
#         else:
#             adjustment = -0.05  # Decrease disease confidence slightly
# 
#         adjusted_pred = np.clip(pred + adjustment, 0, 1)
#         label = "Diseased Leaf" if adjusted_pred > 0.5 else "Healthy Leaf"
#         confidence = (adjusted_pred if label == "Diseased Leaf" else 1 - adjusted_pred) * 100
# 
#         st.write(f"### Selected Symptom: {symptom}")
#         st.write(f"### Result: {label}")
#         st.write(f"### Adjusted Confidence: {confidence:.2f}%")
#

!streamlit run streamlit_app.py &> streamlit_log.txt &

from pyngrok import ngrok
public_url = ngrok.connect(8501, "http")
print(f"Streamlit App running at: {public_url}")



